/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.UserDao;
import model.User;

/**
 *
 * @author Siddhesh
 */
public class ChangeSecurityQuestion extends javax.swing.JFrame {

    public String userEmail;

    /**
     * Creates new form ChangeSecurityQuestion
     */
    public ChangeSecurityQuestion() {
        initComponents();
    }

    public ChangeSecurityQuestion(String email) {
        initComponents();
        userEmail = email;
        txtOldSecurityQue.setEditable(false);
        btnUpdate.setEnabled(false);
    }

    public void validateField() {
        String password = txtPassword.getText();
        String securityQuestion = txtNewSecurityQue.getText();
        String answer = txtNewAns.getText();
        if (!password.equals("") && !securityQuestion.equals("") && !answer.equals("")) {
            btnUpdate.setEnabled(true);
        } else {
            btnUpdate.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChangeSecurityQue = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblOldSecurityQue = new javax.swing.JLabel();
        lblNewSecurityQue = new javax.swing.JLabel();
        lblNewAns = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtNewSecurityQue = new javax.swing.JTextField();
        txtOldSecurityQue = new javax.swing.JTextField();
        txtNewAns = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChangeSecurityQue.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        lblChangeSecurityQue.setForeground(new java.awt.Color(255, 255, 255));
        lblChangeSecurityQue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChangeSecurityQue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
        lblChangeSecurityQue.setText("Change Security Question");
        getContentPane().add(lblChangeSecurityQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 35, -1));

        lblOldSecurityQue.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblOldSecurityQue.setForeground(new java.awt.Color(255, 255, 255));
        lblOldSecurityQue.setText("Old Security Question ");
        getContentPane().add(lblOldSecurityQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        lblNewSecurityQue.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNewSecurityQue.setForeground(new java.awt.Color(255, 255, 255));
        lblNewSecurityQue.setText("New Security Question");
        getContentPane().add(lblNewSecurityQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        lblNewAns.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNewAns.setForeground(new java.awt.Color(255, 255, 255));
        lblNewAns.setText("New Answer");
        getContentPane().add(lblNewAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 360, -1));

        txtNewSecurityQue.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNewSecurityQue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewSecurityQueKeyReleased(evt);
            }
        });
        getContentPane().add(txtNewSecurityQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 360, -1));

        txtOldSecurityQue.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(txtOldSecurityQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 360, -1));

        txtNewAns.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNewAns.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewAnsKeyReleased(evt);
            }
        });
        getContentPane().add(txtNewAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 360, -1));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orsrc59346.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String password = txtPassword.getText();
        String securityQuestion = txtNewSecurityQue.getText();
        String answer = txtNewAns.getText();
        UserDao.chnageSecurityQuestion(userEmail, password, securityQuestion, answer);
        setVisible(false);
        new ChangeSecurityQuestion(userEmail).setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ChangeSecurityQuestion(userEmail).setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        User user=UserDao.getSecurityQuestion(userEmail);
        txtOldSecurityQue.setText(user.getSque());
    }//GEN-LAST:event_formComponentShown

    private void txtNewSecurityQueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewSecurityQueKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtNewSecurityQueKeyReleased

    private void txtNewAnsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewAnsKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtNewAnsKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeSecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeSecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeSecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeSecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeSecurityQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblChangeSecurityQue;
    private javax.swing.JLabel lblNewAns;
    private javax.swing.JLabel lblNewSecurityQue;
    private javax.swing.JLabel lblOldSecurityQue;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtNewAns;
    private javax.swing.JTextField txtNewSecurityQue;
    private javax.swing.JTextField txtOldSecurityQue;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}


//# .........................................
//
//# Project Name : S-Mart Management System 
//# Language Used : Java 
//# Database : MYSQL
//# Developed By : Siddheshwar Koli | Atharva Walke
//# Contact By : siddheshwarkoli10@gmail.com
//
//# .........................................