/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import Common.OpenPdf;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.BillDao;
import dao.CategoryDao;
import dao.ProductDao;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;
import model.Product;
import model.Category;

/**
 *
 * @author Siddhesh
 */
public class PlaceOrder extends javax.swing.JFrame {

    public int billId = 1;
    public int grandTotal = 0;
    public int productPrice = 0;
    public int productTotal = 0;
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobilenoPattern = "^[0-9]*$";
    public String userEmail;

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
    }

    public PlaceOrder(String email) {
        initComponents();
        txtProName.setEditable(false);
        txtProPrice.setEditable(false);
        txtProTotal.setEditable(false);
        btnAddToCart.setEnabled(false);
        btnGenerateBillPrint.setEnabled(false);
        JFormattedTextField tf = ((JSpinner.DefaultEditor) txtProQty.getEditor()).getTextField();
        tf.setEditable(false);
        userEmail = email;
    }

    public void productNameByCategory(String category) {
        DefaultTableModel dtm = (DefaultTableModel) tblOne.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.getAllRecordsByCategory(category);
        Iterator<Product> itr = list.iterator();
        while (itr.hasNext()) {
            Product productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
        }
    }

    public void filterProductByname(String name, String category) {
        DefaultTableModel dtm = (DefaultTableModel) tblOne.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.filterProductByname(name, category);
        Iterator<Product> itr = list.iterator();
        while (itr.hasNext()) {
            Product productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
        }
    }

    public void clearProductFields() {
        txtProName.setText("");
        txtProPrice.setText("");
        txtProQty.setValue(1);
        txtProTotal.setText("");
        btnAddToCart.setEnabled(false);
    }

    public void validateFields() {
        String customerName = txtCustName.getText();
        String customerMobileNo = txtMobNo.getText();
        String customerEmail = txtEmail.getText();
        if (!customerEmail.equals("") && customerMobileNo.matches(mobilenoPattern) && customerMobileNo.length() == 10 && customerEmail.matches(emailPattern) && grandTotal > 0) {
            btnGenerateBillPrint.setEnabled(true);
        } else {
            btnGenerateBillPrint.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlaceOrder = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblBillId = new javax.swing.JLabel();
        lblBillId2 = new javax.swing.JLabel();
        lblGrandTotal000 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtMobNo = new javax.swing.JTextField();
        lblMobNo = new javax.swing.JLabel();
        txtProName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOne = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        lblSearch1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblPrice1 = new javax.swing.JLabel();
        txtProTotal = new javax.swing.JTextField();
        txtProQty = new javax.swing.JSpinner();
        lblQuantity1 = new javax.swing.JLabel();
        txtProPrice = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        btnGenerateBillPrint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTwo = new javax.swing.JTable();
        lblCustDtls1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblGrandTotal = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPlaceOrder.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        lblPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaceOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        lblPlaceOrder.setText("Place Order");
        getContentPane().add(lblPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 10, 35, -1));

        lblBillId.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblBillId.setForeground(new java.awt.Color(255, 255, 255));
        lblBillId.setText("Bill ID");
        getContentPane().add(lblBillId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lblBillId2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblBillId2.setForeground(new java.awt.Color(255, 255, 255));
        lblBillId2.setText("--");
        getContentPane().add(lblBillId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 37, -1));

        lblGrandTotal000.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblGrandTotal000.setForeground(new java.awt.Color(255, 255, 255));
        lblGrandTotal000.setText("000");
        getContentPane().add(lblGrandTotal000, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 570, -1, -1));

        lblName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        txtMobNo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtMobNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobNoKeyReleased(evt);
            }
        });
        getContentPane().add(txtMobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 360, -1));

        lblMobNo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblMobNo.setForeground(new java.awt.Color(255, 255, 255));
        lblMobNo.setText("Mobile Number");
        getContentPane().add(lblMobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        txtProName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtProName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtProName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 360, -1));

        lblEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 37, -1));

        lblCategory.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("Category");
        getContentPane().add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        cmbCategory.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 360, -1));

        lblTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 60, -1));

        tblOne.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tblOne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        tblOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOne);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 360, 270));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));

        lblName2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblName2.setForeground(new java.awt.Color(255, 255, 255));
        lblName2.setText("Name");
        getContentPane().add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, -1, -1));

        txtCustName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtCustName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 360, -1));

        lblSearch1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSearch1.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch1.setText("Search");
        getContentPane().add(lblSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        txtSearch.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 360, -1));

        lblPrice1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblPrice1.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice1.setText("Price");
        getContentPane().add(lblPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 40, -1));

        txtProTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtProTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProTotalKeyReleased(evt);
            }
        });
        getContentPane().add(txtProTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 360, -1));

        txtProQty.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtProQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtProQtyStateChanged(evt);
            }
        });
        getContentPane().add(txtProQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 360, -1));

        lblQuantity1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblQuantity1.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity1.setText("Quantity");
        getContentPane().add(lblQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 60, -1));

        txtProPrice.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtProPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtProPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 360, -1));

        btnAddToCart.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        btnAddToCart.setText("Add To Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 360, -1, -1));

        btnGenerateBillPrint.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGenerateBillPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        btnGenerateBillPrint.setText("Generate Bill & Print");
        btnGenerateBillPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateBillPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, -1, -1));

        tblTwo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tblTwo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        tblTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTwoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTwo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 363, 410));

        lblCustDtls1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCustDtls1.setForeground(new java.awt.Color(255, 255, 255));
        lblCustDtls1.setText("Customer Details");
        getContentPane().add(lblCustDtls1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 360, -1));

        lblGrandTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblGrandTotal.setText("Grand Total: Rs.");
        getContentPane().add(lblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, -1, -1));

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orsrc37697.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 640));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orsrc37697.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 220, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home(userEmail).setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtMobNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobNoKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtMobNoKeyReleased

    private void txtProNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProNameKeyReleased

    private void txtCustNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustNameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtCustNameKeyReleased

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String name = txtSearch.getText();
        String category = (String) cmbCategory.getSelectedItem();
        filterProductByname(name, category);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtProTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProTotalKeyReleased

    private void txtProPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProPriceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProPriceKeyReleased

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        String name = txtProName.getText();
        String price = txtProPrice.getText();
        String quantity = String.valueOf(txtProQty.getValue());
        DefaultTableModel dtm = (DefaultTableModel) tblTwo.getModel();
        dtm.addRow(new Object[]{name, price, quantity, productTotal});
        grandTotal = grandTotal + productTotal;
        lblGrandTotal000.setText(String.valueOf(grandTotal));
        clearProductFields();
        validateFields();
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId = Integer.parseInt(BillDao.getId());
        lblBillId2.setText(BillDao.getId());
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while (itr.hasNext()) {
            Category categoryObj = itr.next();
            cmbCategory.addItem(categoryObj.getName());
        }
        String category = (String) cmbCategory.getSelectedItem();
        productNameByCategory(category);
    }//GEN-LAST:event_formComponentShown

    private void tblOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOneMouseClicked
        // TODO add your handling code here:
        int index = tblOne.getSelectedRow();
        TableModel model = tblOne.getModel();
        String productName = model.getValueAt(index, 0).toString();
        Product product = ProductDao.getProductByname(productName);
        txtProName.setText(product.getName());
        txtProPrice.setText(product.getPrice());
        txtProQty.setValue(1);
        txtProTotal.setText(product.getPrice());
        productPrice = Integer.parseInt(product.getPrice());
        productTotal = Integer.parseInt(product.getPrice());
        btnAddToCart.setEnabled(true);
    }//GEN-LAST:event_tblOneMouseClicked

    private void txtProQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtProQtyStateChanged
        // TODO add your handling code here:
        int quantity = (Integer) txtProQty.getValue();
        if (quantity <= 1) {
            txtProQty.setValue(1);
            quantity = 1;
        }
        productTotal = productPrice * quantity;
        txtProTotal.setText(String.valueOf(productTotal));
    }//GEN-LAST:event_txtProQtyStateChanged

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
        String category = (String) cmbCategory.getSelectedItem();
        productNameByCategory(category);
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearProductFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void btnGenerateBillPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillPrintActionPerformed
        // TODO add your handling code here:
        String customerName = txtCustName.getText();
        String customerMobileNo = txtMobNo.getText();
        String customerEmail = txtEmail.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todaydate = dFormat.format(date);
        String total = String.valueOf(grandTotal);
        String createdBy = userEmail;
        Bill bill = new Bill();
        bill.setId(billId);
        bill.setName(customerName);
        bill.setMobileno(customerMobileNo);
        bill.setEmail(customerEmail);
        bill.setDate(todaydate);
        bill.setTotal(total);
        bill.setCreatedBy(createdBy);
        BillDao.save(bill);

        //Creating Document
        String path = "D:\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + billId + ".pdf"));
            doc.open();
            Paragraph cafeName = new Paragraph("                                                           Cafe Management Syatem\\n");
            doc.add(cafeName);
            Paragraph starLine = new Paragraph("**************************************************************************************************************************");
            doc.add(starLine);
            Paragraph paragraph3 = new Paragraph("\tBill ID:" + billId + "\nCustomer Name: " + customerName + "\nTotal Paid: " + grandTotal);
            doc.add(paragraph3);
            doc.add(starLine);
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("Name");
            tb1.addCell("Price");
            tb1.addCell("Quantity");
            tb1.addCell("Total");
            for (int i = 0; i < tblTwo.getRowCount(); i++) {
                String n = tblTwo.getValueAt(i, 0).toString();
                String d = tblTwo.getValueAt(i, 1).toString();
                String r = tblTwo.getValueAt(i, 2).toString();
                String q = tblTwo.getValueAt(i, 3).toString();
                tb1.addCell(n);
                tb1.addCell(d);
                tb1.addCell(r);
                tb1.addCell(q);
            }
            doc.add(tb1);
            doc.add(starLine);
            Paragraph thanksMsg = new Paragraph("Thank You, Please visit Again.");
            doc.add(thanksMsg);

            //Open PDF
            OpenPdf.openById(String.valueOf(billId));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        setVisible(false);
        new PlaceOrder(createdBy).setVisible(true);
    }//GEN-LAST:event_btnGenerateBillPrintActionPerformed

    private void tblTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTwoMouseClicked
        // TODO add your handling code here:
        int index = tblTwo.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this product", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = tblTwo.getModel();
            String total = model.getValueAt(index, 3).toString();
            grandTotal = grandTotal - Integer.parseInt(total);
            lblGrandTotal000.setText(String.valueOf(grandTotal));
            ((DefaultTableModel) tblTwo.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_tblTwoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerateBillPrint;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBillId;
    private javax.swing.JLabel lblBillId2;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCustDtls1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblGrandTotal000;
    private javax.swing.JLabel lblMobNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblPlaceOrder;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblQuantity1;
    private javax.swing.JLabel lblSearch1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblOne;
    private javax.swing.JTable tblTwo;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobNo;
    private javax.swing.JTextField txtProName;
    private javax.swing.JTextField txtProPrice;
    private javax.swing.JSpinner txtProQty;
    private javax.swing.JTextField txtProTotal;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}


//# .........................................
//
//# Project Name : S-Mart Management System 
//# Language Used : Java 
//# Database : MYSQL
//# Developed By : Siddheshwar Koli | Atharva Walke
//# Contact By : siddheshwarkoli10@gmail.com
//
//# .........................................
